fixtures:
  repositories:
    apt:
      repo: 'git://github.com/puppetlabs/puppetlabs-apt.git'
      ref: '1.4.2'
    inifile:
      repo: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.4.2'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.10.0'
    yumrepo:
      repo: 'git://github.com/puppetlabs/puppetlabs-yumrepo_core'
      ref:  '1.0.0'
    zypprepo:
      repo: 'git://github.com/voxpupuli/puppet-zypprepo.git'
      ref: 'v1.0.2'
  symlinks:
    vmware: "#{source_dir}"
